"""
Django settings for incomeexpenses project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
# pip install python-decouple
from pathlib import Path
from decouple import config
from django.contrib import messages
import django_heroku



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
##Change 1:
#SECRET_KEY = '$-s91w(u5rbtyt4akka%$1(z50=q#@$9@1cr=uui7jpfo6+!^k'

# SECURITY WARNING: don't run with debug turned on in production!
##Change 2:
#DEBUG = True

ALLOWED_HOSTS = ['incomeexpenses.herokuapp.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'expenses',
    'incomes',
    'authentication',
    'userpreferences',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'incomeexpenses.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'incomeexpenses.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases



# visit for settings: https://djangostars.com/blog/configuring-django-settings-best-practices/
# https://djangostars.com/blog/configuring-django-settings-best-practices/
# pip install psycopg2
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_USER_PASSWORD'),
        'HOST': config('DB_HOST'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR/"static_root"
STATICFILES_DIRS = [
    BASE_DIR/"static"  # if we keep the static file inside expenseswebsite. than, expenseswebsite/static will base_dir
]


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR/"static/images"
django_heroku.settings(locals())  # https://pypi.org/project/django-heroku/

MESSAGE_TAGS = {
    messages.ERROR: 'danger'
}

# email configuration for password reset

# https://docs.djangoproject.com/en/3.1/topics/email/#smtp-backend
# https://blog.mailtrap.io/django-send-email/
# go to https://myaccount.google.com/lesssecureapps and turn on
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "ursula.friedman.01@gmail.com"
EMAIL_HOST_PASSWORD = "ursula.friedman.01@gmail.com"
DEFAULT_FROM_EMAIL = "51Monirul@thaminA95"



#########################Heroku deployment#############################
# pip install gunicorn
SECRET_KEY = config('SECRET_KEY') #alternative of Change 1.
DEBUG = (config('DEBUG_VALUE') == 'True') #alternative of Change 1.

# https://pypi.org/project/django-heroku/
# pip install django-heroku
import django_heroku
django_heroku.settings(locals())
